server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/chatbot_db?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: 1234

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect





